Category.create!([
  {kind: 0, title: "JOGOS"},
  {kind: 0, title: "FILME/TEMATIZAÇÃO"},
  {kind: 0, title: "SIMULAÇÃO"},
  {kind: 0, title: "SISTEMATIZAÇÃO"},
  {kind: 0, title: "MODELIZAÇÃO"},
  {kind: 0, title: "DISCUSSÃO/DEBATE"},
  {kind: 0, title: "PROBLEMATIZAÇÃO"},
  {kind: 0, title: "DRAMATIZAÇÃO "}
])
Teaching.create!([
  {link: "https://www.flipsnack.com/Eveli/revista-genetica-na-escola-volume-1-numero-2-2006.html?p=14", category_id: 1, title: "AJUDANDO A FIXAR OS CONCEITOS DE GENÉTICA", views: nil, unity: "1", topics: "5"},
  {link: "https://www.flipsnack.com/Eveli/revista-genetica-na-escola-volume-1-numero-2-2006.html?p=19", category_id: 1, title: "GENÉTICA REVISANDO E FIXANDO CONCEITOS", views: nil, unity: "1", topics: "5"},
  {link: "https://www.flipsnack.com/Eveli/revista-genetica-na-escola-volume-1-numero-2-2006.html?p=33", category_id: 4, title: "MENDEL ENROLADO NA DUPLA-HÉLICE", views: nil, unity: "1", topics: "5"},
  {link: "https://www.flipsnack.com/Eveli/revista-genetica-na-escola-volume-2-numero-1-2007.html?p=11", category_id: 4, title: "DOS GENES AOS FENÓTIPOS", views: nil, unity: "1", topics: "2,3,5"},
  {link: "https://www.flipsnack.com/Eveli/revista-genetica-na-escola-volume-4-numero-1-2009.html?p=8", category_id: 1, title: "SISTEMA SANGUÍNEO SEM MISTÉRIO: uma proposta alternativa", views: nil, unity: "1,2", topics: "2,3,5,8"},
  {link: "https://www.flipsnack.com/Eveli/revista-genetica-na-escola-volume-4-numero-1-2009.html?p=11", category_id: 1, title: "“NA TRILHA DO SANGUE”: o jogo dos grupos sanguíneos", views: nil, unity: "1,2", topics: "2,3,5,8"},
  {link: "https://www.flipsnack.com/Eveli/revista-genetica-na-escola-volume-4-numero-1-2009.html?p=18", category_id: 4, title: "O “X” DA QUESTÃO: a diversidade gerada pela segregação cromossômica independente e a cor da pelagem de gatos", views: nil, unity: "1", topics: "2,3,5"},
  {link: "https://www.flipsnack.com/Eveli/revista-genetica-na-escola-volume-4-numero-2-2009.html?p=31", category_id: 1, title: "GENÉTICA NO COTIDIANO: o sistema ABO na transfusão sanguínea", views: nil, unity: "1,2", topics: "5,8"},
  {link: "https://www.flipsnack.com/Eveli/revista-genetica-na-escola-volume-5-numero-1-2010.html?p=6", category_id: 1, title: "“CRUZAMENTOS MENDELIANOS”: o bingo das ervilhas", views: nil, unity: "1", topics: "2,3,5"},
  {link: "https://www.flipsnack.com/Eveli/revista-genetica-na-escola-volume-5-numero-2-2010.html?p=38", category_id: 5, title: "BRINCANDO COM O SISTEMA SANGUÍNEO: proposta alternativa para o ensino dos grupos sanguíneos ABO", views: nil, unity: "1,2", topics: "5,8"},
  {link: "https://www.flipsnack.com/Eveli/revista-genetica-na-escola-volume-6-numero-1-ft3eomm9v.html?p=2", category_id: 3, title: "AÇÃO DE DOIS ANTÍGENOS: vai um refresco aí?", views: nil, unity: "1,2", topics: "5,8"},
  {link: "https://www.flipsnack.com/Eveli/revista-genetica-na-escola-volume-6-numero-2-2011.html?p=47", category_id: 1, title: "JOGO DA QUEIMADA: uma prática para o ensino da genética", views: nil, unity: "1,2", topics: "2,3,5,6,8"},
  {link: "https://www.flipsnack.com/Eveli/revista-genetica-na-escola-volume-8-numero-2-2013.html?p=4", category_id: 4, title: "HEREDOGRAMAS DOS ESTUDANTES: das Anágrafes Paroquiais para a Escola", views: nil, unity: "1", topics: "5,6"},
  {link: "https://www.flipsnack.com/Eveli/revista-genetica-na-escola-volume-8-numero-2-2013.html?p=22", category_id: 1, title: "“Tá ligado?”: uma forma lúdica de aprender ligação gênica", views: nil, unity: "1", topics: "2,3,5"},
  {link: "https://www.flipsnack.com/Eveli/revista-genetica-na-escola-volume-9-numero-1-2014.html?p=4", category_id: 3, title: "CANUDINHOS: uma simulação para aprender genética de populações e seleção natural", views: nil, unity: "1,2", topics: "2,3,5,8"},
  {link: "https://www.flipsnack.com/Eveli/revista-genetica-na-escola-volume-9-numero-1-2014.html?p=32", category_id: 1, title: "DOMINÓ GÊNICO: interagindo para compreender a interação gênica", views: nil, unity: "1", topics: "2,5"},
  {link: "https://www.flipsnack.com/Eveli/revista-genetica-na-escola-volume-9-numero-1-2014.html?p=48", category_id: 1, title: "O JOGO DA RESPOSTA AO DANO NO DNA", views: nil, unity: "2", topics: "9,10"},
  {link: "https://www.flipsnack.com/Eveli/revista-genetica-na-escola-volume-10-numero-2.html?p=50", category_id: 4, title: "O HEREDOGRAMA NAS SÉRIES INICIAIS DO ENSINO FUNDAMENTAL", views: nil, unity: "1", topics: "2,5,6"},
  {link: "https://www.flipsnack.com/Eveli/revista-genetica-na-escola-volume-3-numero-1-2008.html?p=2", category_id: 4, title: "ACONSELHAMENTO GENÉTICO: o exemplo do casamento entre primos", views: nil, unity: "1,2,4", topics: "2,3,5,6,8,11,16"},
  {link: "https://www.flipsnack.com/Eveli/revista-genetica-na-escola-volume-3-numero-1-2008.html?p=34", category_id: 2, title: "QUESTÃO DE SENSIBILIDADE: um filme para conversar sobre a homossexualidade e conceitos básicos de genética", views: nil, unity: "2,3,4", topics: "11,12,14,16"},
  {link: "https://www.flipsnack.com/Eveli/revista-genetica-na-escola-volume-4-numero-2-2009.html?p=37", category_id: 6, title: "GENÉTICA E ÉTICA EM PAINÉIS DIDÁTICOS", views: nil, unity: "2,4", topics: "7,16"},
  {link: "https://www.flipsnack.com/Eveli/revista-genetica-na-escola-volume-5-numero-1-2010.html?p=2", category_id: 3, title: "O TESTE DE DNA NA SALA DE AULA: é possível ensinar Biologia partir de temas atuais?", views: nil, unity: "1,3,4", topics: "3,5,14,16"},
  {link: "https://www.flipsnack.com/Eveli/revista-genetica-na-escola-volume-5-numero-1-2010.html?p=44", category_id: 4, title: "HIPERTENSÃO: uma herança genética multifatorial", views: nil, unity: "1,2,4", topics: "1,5,8,16"},
  {link: "https://www.flipsnack.com/Eveli/revista-genetica-na-escola-volume-5-numero-2-2010.html?p=2", category_id: 1, title: "“CONTÉM FENILALANINA, POSSO COMER?”", views: nil, unity: "1,2,3", topics: "5,8,13"},
  {link: "https://www.flipsnack.com/Eveli/revista-genetica-na-escola-volume-5-numero-2-2010.html?p=24", category_id: 3, title: "CAÇANDO GENES", views: nil, unity: "1,2,3", topics: "3,5,6,8,11,12,14"},
  {link: "https://www.flipsnack.com/Eveli/revista-genetica-na-escola-volume-6-numero-1-ft3eomm9v.html?p=5", category_id: 3, title: "UMA SIMULAÇÃO DE TESTE DE PATERNIDADE: quem é o pai do bezerro?", views: nil, unity: "1,3", topics: "5,14"},
  {link: "https://www.flipsnack.com/Eveli/revista-genetica-na-escola-volume-8-numero-1-2013.html?p=10", category_id: 3, title: "IDENTIFICANDO O SISTEMA DE ACASALAMENTO EM AVES", views: nil, unity: "1,3", topics: "3,5,14"},
  {link: "https://www.flipsnack.com/Eveli/revista-genetica-na-escola-volume-8-numero-1-2013.html?p=18", category_id: 4, title: "DISPERSÃO DO PÓLEN ENTRE PEQUIZEIROS: uma atividade para a genética no ensino superior", views: nil, unity: "1,3", topics: "3,5,14"},
  {link: "https://www.flipsnack.com/Eveli/revista-genetica-na-escola-volume-8-numero-1-2013.html?p=28", category_id: 4, title: "IDENTIFICAÇÃO DE ESPÉCIE E DO SEU LOCAL DE ORIGEM PARA A RESOLUÇÃO DE CRIMES CONTRA A FAUNA BRASILEIRA: uma atividade para o ensino de genética forense", views: nil, unity: "1,3", topics: "3,5,14"},
  {link: "https://www.flipsnack.com/Eveli/revista-genetica-na-escola-volume-9-numero-2-2014.html?p=28", category_id: 4, title: "AVALIAÇÃO DA DEPRESSÃO ENDOGÂMICA EM POPULAÇÕES DE ARATICUNZEIRO: apoio pedagógico ao Ensino de Genética", views: nil, unity: "1,3", topics: "3,5,14"},
  {link: "https://www.flipsnack.com/Eveli/revista-genetica-na-escola-volume-9-numero-2-2014.html?p=48", category_id: 4, title: "A GENÉTICA CONTRA OS CRIMES AMBIENTAIS: identificação de madeira ilegal provenientes de unidades de conservação utilizando marcador molecular", views: nil, unity: "1,3", topics: "3,5,14"},
  {link: "https://www.flipsnack.com/Eveli/revista-genetica-na-escola-volume-11-numero-1.html?p=30", category_id: 2, title: "GUIA DO EDUCADOR PARA O FILME X-MEN PRIMEIRA CLASSE", views: nil, unity: "1", topics: "1,4,5"},
  {link: "https://www.flipsnack.com/Eveli/revista-genetica-na-escola-volume-11-numero-1.html?p=48", category_id: 3, title: "SIMULANDO A RELAÇÃO ENTRE MUTAÇÃO E CÂNCER NA SALA DE AULA", views: nil, unity: "1,2", topics: "5,9,10"},
  {link: "https://www.flipsnack.com/Eveli/revista-genetica-na-escola-volume-11-numero-2-suplemento.html?p=80", category_id: 1, title: "QUE ERVILHA SOU EU?", views: nil, unity: "1", topics: "2,3,5"},
  {link: "https://www.flipsnack.com/Eveli/revista-genetica-na-escola-volume-11-numero-2-suplemento.html?p=114", category_id: 1, title: "EMBARALHANDO MENDEL E SUAS LEIS", views: nil, unity: "1", topics: "2,3,5"},
  {link: "https://www.flipsnack.com/Eveli/revista-genetica-na-escola-volume-11-numero-2-suplemento.html?p=142", category_id: 1, title: "CARTEANDO COM MENDEL", views: nil, unity: "1", topics: "2,3,5"},
  {link: "https://www.flipsnack.com/Eveli/revista-gen-tica-na-escola-volume-12-n-mero-1.html?p=46", category_id: 4, title: "COLORAÇÃO DA PELAGEM CANINA: integrando conceitos básicos de genética clássica", views: nil, unity: "1", topics: "2,3,5"},
  {link: "https://www.flipsnack.com/Eveli/revista-gen-tica-na-escola-volume-12-n-mero-1.html?p=74", category_id: 4, title: "UTILIZAÇÃO DE MODELOS DE DROSOPHILA NO ESTUDO DE PADRÕES DE HERANÇA AUTOSSÔMICA E LIGADA AO SEXO", views: nil, unity: "1", topics: "2,3,5"},
  {link: "https://www.flipsnack.com/Eveli/revista-gen-tica-na-escola-volume-12-n-mero-1.html?p=90", category_id: 5, title: "MATERIAL DIDÁTICO PARA O ENSINO INCLUSIVO DE HERANÇA GENÉTICA", views: nil, unity: "1", topics: "2,3,5"},
  {link: "https://www.flipsnack.com/Eveli/revista-gen-tica-na-escola-volume-12-n-mero-2.html?p=66", category_id: 4, title: "OS GENES DE COLORAÇÃO MC1R E ASIP COMO MODELOS PARA O ENSINO DE GENÉTICA: dominância e interação gênica", views: nil, unity: "1", topics: "2,3,5"},
  {link: "https://www.flipsnack.com/Eveli/revista-genetica-na-escola-volume-1-numero-2-2006.html?p=4", category_id: 2, title: "O ÓLEO DE LORENZO: O USO DO CINEMA PARA CONTEXTUALIZAR O ENSINO DE GENÉTICA E DISCUTIR A CONSTRUÇÃO DO CONHECIMENTO CIENTÍFICO", views: nil, unity: "1,2,3,4", topics: "2,5,6,8,11,12,16,17,18,19"}
])
Unity.create!([
  {name: "Listar várias características humanas ou de animais e plantas, distinguindo as hereditárias das congênitas e adquiridas.", position: 1},
  {name: "Identificar, a partir de resultados de cruzamentos, os princípios básicos que regem a transmissão de características hereditárias e aplicá-los para interpretar o surgimento de determinadas características.", position: 2},
  {name: "Utilizar noções básicas de probabilidade para prever resultados de cruzamentos e para resolver problemas envolvendo características diversas.", position: 3},
  {name: "Analisar textos históricos para identificar concepções pré-mendelianas sobre a hereditariedade.", position: 4},
  {name: "Identificar e utilizar os códigos usados para representar as características genéticas em estudo.", position: 5},
  {name: "Construir heredogramas a partir de dados levantados pelos alunos (junto a familiares ou conhecidos) sobre a transmissão de certas características hereditárias.", position: 6},
  {name: "Levantar dados sobre as características que historicamente são consideradas para definir os agrupamentos raciais humanos em caucasóides, negróides e orientais, identificando-as como correspondentes a apenas uma fração mínima do genoma humano.", position: 7},
  {name: "Analisar aspectos genéticos do funcionamento do corpo humano como alguns distúrbios metabólicos (albinismo, fenilcetonúria), ou os relacionados aos antígenos e anticorpos, como os grupos sanguíneos e suas incompatibilidades, transplantes e doenças auto-imunes.", position: 8},
  {name: "Distinguir uma célula cancerosa de uma normal, apontando suas anomalias genéticas, além de alterações morfológicas e metabólicas.", position: 9},
  {name: "Identificar fatores ambientais – vírus, radiações e substâncias químicas – que aumentam o risco de desenvolver câncer e medidas que podem reduzir esses riscos, como limitar a exposição à luz solar.", position: 10},
  {name: "Avaliar a importância do aconselhamento genético, analisando suas finalidades, o acesso que a população tem a esses serviços e seus custos.", position: 11},
  {name: "Identificar as técnicas moleculares utilizadas para a detecção precoce de doenças genéticas, seus custos, levantando informações junto a profissionais e serviços de saúde.", position: 12},
  {name: "Identificar o papel da terapia gênica no tratamento de doenças genéticas e seu uso na medicina brasileira, pesquisando textos ou entrevistando profissionais da área.", position: 13},
  {name: "Reconhecer a importância dos testes de DNA nos casos de determinação da paternidade, investigação criminal e identificação de indivíduos.", position: 14},
  {name: "Compreender a natureza dos projetos genomas, especialmente os existentes no país, listando seus objetivos como identificação dos genes, da sequência do DNA e armazenamento dessas informações em bancos de dados.", position: 15},
  {name: "Reconhecer a importância dos procedimentos éticos no uso da informação genética para promover a saúde do ser humano sem ferir a sua privacidade e sua dignidade.", position: 16},
  {name: "Posicionar-se perante o uso das terapias genéticas, distinguindo aquelas que são eticamente recomendadas daquelas que devem ser proibidas.", position: 17},
  {name: "Avaliar a importância do aspecto econômico envolvido na utilização da manipulação genética em saúde: o problema das patentes biológicas e a exploração comercial das descobertas das tecnologias de DNA.", position: 18},
  {name: "Posicionar-se perante a polêmica sobre o direito de propriedade das descobertas relativas ao genoma humano, analisando argumentos de diferentes profissionais.", position: 19}
])
